TRUNCATE "Card" RESTART IDENTITY CASCADE;
TRUNCATE "Lock" RESTART IDENTITY CASCADE;
TRUNCATE "Dock" RESTART IDENTITY CASCADE;
TRUNCATE "EBike" RESTART IDENTITY CASCADE;
TRUNCATE "Bike" RESTART IDENTITY CASCADE;